version: "3.9"

networks:
  reverse-proxy:
    external: true

configs:
  docker_yaml:
    name: docker_yaml_${TAG}
    file: ./docker.yaml

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    configs:
      - source: static
        target: /app/config/docker.yaml
    ports:
      - 3000:3000
    volumes:
      - /mnt/user/docker/volumes/homepage:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations, see alternative methods
    environment:
      PUID: 99
      PGID: 100
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - reverse-proxy
