---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Unraid:
    - Databases:
        href: http://192.168.2.2:8080
        description: Adminer to access postgres
        icon: https://raw.githubusercontent.com/Actuary-LLC/homepage/5ee29b69f6c410ffaaa6f374680a996f50557c52/images/unraid.svg

- My Second Group:
    - My Second Service:
        href: http://localhost/
        description: Homepage is the best

