---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Unraid:
    - Databases:
        href: http://192.168.2.2:8080
        description: Adminer to access postgres
        icon: https://raw.githubusercontent.com/Actuary-LLC/homepage/5ee29b69f6c410ffaaa6f374680a996f50557c52/images/unraid.svg

- My Second Group:
    - My Second Service:
        href: http://localhost/
        description: Homepage is the best

- glances:
    url: http://unraid.lan:1208
    #username: user # optional if auth enabled in Glances
    #password: pass # optional if auth enabled in Glances
    version: 4 # required only if running glances v4 or higher, defaults to 3
    cpu: true # optional, enabled by default, disable by setting to false
    mem: true # optional, enabled by default, disable by setting to false
    cputemp: true # disabled by default
    uptime: true # disabled by default
    disk: / # disabled by default, use mount point of disk(s) in glances. Can also be a list (see below)
    diskUnits: bytes # optional, bytes (default) or bbytes. Only applies to disk
    expanded: true # show the expanded view
    label: Unraid # optional
