---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Unraid:
    - Databases:
        href: http://192.168.2.2:8080
        description: Adminer to access postgres
        icon: https://raw.githubusercontent.com/Actuary-LLC/homepage/5ee29b69f6c410ffaaa6f374680a996f50557c52/images/unraid.svg

- My Second Group:
    - My Second Service:
        href: http://localhost/
        description: Homepage is the best
        widget:
          type: glances
          url: http://192.168.2.2:61208
          #username: user # optional if auth enabled in Glances
          #password: pass # optional if auth enabled in Glances
          version: 4 # required only if running glances v4 or higher, defaults to 3
          metric: cpu
          diskUnits: bytes # optional, bytes (default) or bbytes. Only applies to disk
          refreshInterval: 5000 # optional - in milliseconds, defaults to 1000 or more, depending on the metric
          pointsLimit: 15 # optional, defaults to 15
