---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

#- Unraid:
#    - Databases:
#        href: http://192.168.2.2:8080
#        description: Adminer to access postgres
#        icon: https://raw.githubusercontent.com/Actuary-LLC/homepage/5ee29b69f6c410ffaaa6f374680a996f50557c52/images/unraid.svg   
#- Databases:
#    - Postgres:
#        icon: https://github.com/Actuary-LLC/homepage/blob/main/images/postgres.svg
#        href: http://unraid.lan:8080
#        description: Adminer access to Postgres database


#Hardware - Services
- Unraid:
    - Info:
        widget:
          type: glances
          url: http://192.168.2.2:61208
          version: 4
          metric: info
          diskUnits: bytes
          refreshInterval: 5000
          pointsLimit: 15
    - CPU Usage:
        widget:
          type: glances
          url: http://192.168.2.2:61208
          version: 4
          metric: cpu
          diskUnits: bytes
          refreshInterval: 5000
          pointsLimit: 15
    - RAM:
        widget:
          type: glances
          url: http://192.168.2.2:61208
          version: 4
          metric: memory
          diskUnits: bytes
          refreshInterval: 5000
          pointsLimit: 15
    - Processes:
        widget:
          type: glances
          url: http://192.168.2.2:61208
          metric: process
          version: 4
    - Network Usage:
        widget:
          type: glances
          url: http://192.168.2.2:61208
          metric: network:eth1
          version: 4
          diskUnits: bytes
          refreshInterval: 5000
          pointsLimit: 15
    - ZFS Pool:
        widget:
          type: glances
          url: http://192.168.2.2:61208
          metric: fs:/mnt/ssd
          version: 4
          diskUnits: bytes
          refreshInterval: 5000
          pointsLimit: 15
    - Array Disk 1:
        widget:
          type: glances
          url: http://192.168.2.2:61208
          metric: disk:/mnt/user/library
          version: 4
          diskUnits: bytes
          refreshInterval: 5000
          pointsLimit: 15
    - Array Disk 2:
        widget:
          type: glances
          url: http://192.168.2.2:61208
          metric: fs:/mnt/user0/
          version: 4
          diskUnits: bytes
          refreshInterval: 5000
          pointsLimit: 15
    - Array Disk 3:
        widget:
          type: glances
          url: http://192.168.2.2:61208
          metric: fs:/mnt/disk3
          version: 4
          diskUnits: bytes
          refreshInterval: 5000
          pointsLimit: 15
- Coral:
    - System:
        widget:
          type: glances
          url: http://192.168.2.3:61208
          version: 4
          metric: info
          diskUnits: bytes
          refreshInterval: 5000
          pointsLimit: 15
    - CPU Usage:
        widget:
          type: glances
          url: http://192.168.2.3:61208
          version: 4
          metric: cpu
          diskUnits: bytes
          refreshInterval: 5000
          pointsLimit: 15
    - Memory:
        widget:
          type: glances
          url: http://192.168.2.3:61208
          metric: memory
          version: 4
    - Core Temperature:
        widget:
          type: glances
          url: http://192.168.2.3:61208
          metric: sensor:Tctl
          version: 4
    - Processes:
        widget:
          type: glances
          url: http://192.168.2.3:61208
          metric: process
          version: 4
    - Network:
        widget:
          type: glances
          url: http://192.168.2.3:61208
          metric: network:enp2s0f0
          version: 4
          diskUnits: bytes
          refreshInterval: 5000
          pointsLimit: 15