---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

#- Unraid:
#    - Databases:
#        href: http://192.168.2.2:8080
#        description: Adminer to access postgres
#        icon: https://raw.githubusercontent.com/Actuary-LLC/homepage/5ee29b69f6c410ffaaa6f374680a996f50557c52/images/unraid.svg   

- Data:
    - Postgres:
        href: http://192.168.2.2:8080
        icon: https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Postgresql_elephant.svg/540px-Postgresql_elephant.svg.png?20080116191800
        description: Adminer access to Postgres database
#- Group A:
#    - Postgres:
#        #
#        href: http://unraid.lan:8080
#        description: Adminer access to Postgres database

#Hardware - Services
- Unraid:
    - Info:
        widget:
          type: glances
          url: http://192.168.2.2:61208
          version: 4
          metric: info
          diskUnits: bytes
          refreshInterval: 1000
          pointsLimit: 15
    - Core Temperature:
        widget:
          type: glances
          url: http://192.168.2.2:61208
          metric: sensor:Package id 0
          version: 4
    - Processes:
        widget:
          type: glances
          url: http://192.168.2.2:61208
          metric: process
          version: 4
    - Network Usage:
        widget:
          type: glances
          url: http://192.168.2.2:61208
          metric: network:eth1
          version: 4
          diskUnits: bytes
          refreshInterval: 1000
          pointsLimit: 15
    - CPU Usage:
        widget:
          type: glances
          url: http://192.168.2.2:61208
          version: 4
          metric: cpu
          diskUnits: bytes
          refreshInterval: 200
          pointsLimit: 15
    - RAM:
        widget:
          type: glances
          url: http://192.168.2.2:61208
          version: 4
          metric: memory
          diskUnits: bytes
          refreshInterval: 1000
          pointsLimit: 15
    - ZFS Pool:
        widget:
          type: glances
          url: http://192.168.2.2:61208
          metric: fs:/mnt/ssd
          version: 4
          diskUnits: bytes
          refreshInterval: 1000
          pointsLimit: 15
- Unraid Array:
    - Array Parity:
        widget:
          type: glances
          url: http://192.168.2.2:61208
          metric: disk:sdi
          version: 4
          diskUnits: bytes
          refreshInterval: 1000
          pointsLimit: 15
    - Array Disk 1:
        widget:
          type: glances
          url: http://192.168.2.2:61208
          metric: disk:sdb
          version: 4
          diskUnits: bytes
          refreshInterval: 1000
          pointsLimit: 15
    - Array Disk 2:
        widget:
          type: glances
          url: http://192.168.2.2:61208
          metric: disk:sdc
          version: 4
          diskUnits: bytes
          refreshInterval: 1000
          pointsLimit: 15
    - Array Disk 3:
        widget:
          type: glances
          url: http://192.168.2.2:61208
          metric: disk:sdh
          version: 4
          diskUnits: bytes
          refreshInterval: 1000
          pointsLimit: 15
- Coral:
    - System:
        widget:
          type: glances
          url: http://192.168.2.3:61208
          version: 4
          metric: info
          diskUnits: bytes
          refreshInterval: 5000
          pointsLimit: 15
    - Processes:
        widget:
          type: glances
          url: http://192.168.2.3:61208
          version: 4
          metric: process
          diskUnits: bytes
          refreshInterval: 1000
          pointsLimit: 15
    - Core Temperature:
        widget:
          type: glances
          url: http://192.168.2.3:61208
          metric: sensor:Tctl
          version: 4
    - Network:
        widget:
          type: glances
          url: http://192.168.2.3:61208
          metric: network:eth0
          version: 4
          diskUnits: bytes
          refreshInterval: 1000
          pointsLimit: 15
    - CPU Usage:
        widget:
          type: glances
          url: http://192.168.2.3:61208
          version: 4
          metric: cpu
          diskUnits: bytes
          refreshInterval: 1000
          pointsLimit: 15
    - Memory:
        widget:
          type: glances
          url: http://192.168.2.3:61208
          metric: memory
          version: 4
          diskUnits: bytes
          refreshInterval: 1000
          pointsLimit: 15
- Vortex:
    - Proxmox VE:
        widget:
          type: proxmox
          url: http://192.168.209.195:8006
          username: ${VORTEX_PROXMOX_TOKEN_ID}
          password: ${VORTEX_PROXMOX_SECRET}
          #node: pve-1 # optional
