name: 'Homepage'
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy-homepage:
    runs-on: [traefik]
    env:
      TAG: ${{ github.sha }}
      OPENWEATHER_API_TOKEN: ${{ secrets.OPENWEATHER_API_TOKEN }}
      VORTEX_PROXMOX_TOKEN_ID: ${{ vars.VORTEX_PROXMOX_TOKEN_ID }}
      VORTEX_PROXMOX_SECRET: ${{ secrets.VORTEX_PROXMOX_SECRET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Configure application
        run: |
          sed -i 's/${LATITUDE}/${{ secrets.LATITUDE }}/' widgets.yaml
          sed -i 's/${LONGITUDE}/${{ secrets.LONGITUDE }}/' widgets.yaml
          cat widgets.yaml
          sed -i 's/${OPENWEATHER_API_TOKEN}/${{ secrets.OPENWEATHER_API_TOKEN }}/' settings.yaml
          cat settings.yaml
          sed -i 's/${VORTEX_PROXMOX_TOKEN_ID}/${{ vars.VORTEX_PROXMOX_TOKEN_ID }}/' services.yaml
          sed -i 's/${VORTEX_PROXMOX_SECRET}/${{ secrets.VORTEX_PROXMOX_SECRET }}/' services.yaml
          cat services.yaml
      - name: Remove and redeploy services
        run: |
          SERVICES=("homepage_homepage") 
          for SERVICE_NAME in "${SERVICES[@]}"; do
            if docker service ls | grep -q $SERVICE_NAME; then
              docker service rm $SERVICE_NAME;
              echo "Service $SERVICE_NAME removed."
            else echo "Service $SERVICE_NAME is not running."
            fi
          done
      - run: docker stack deploy -c homepage.yaml homepage
